id: I9B9999B9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-17T10:00:06+00:00'
last_modified: '2022-06-15T17:28:01.825926+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD17467
  title: ཏཱ་རེ་ལྷ་མོ་དང་ནམ་སྤྲུལ་འཇིགས་མེད་ཕུན་ཚོགས་ཀྱི་གཏེར་ཆོས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    AA6E:
      image_group_id: I4PD2916
      title: Volume 1 of tA re lha mo dang nam sprul 'jigs med phun tshogs kyi gter
        chos/
      total_pages: 298
      order: 1
      base_file: AA6E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
